version: '2'
services:
  apache:
    container_name: apache
    image: docker-repo.tier1.es:5043/producto/demo/comerzzia/apache:2.4
    environment:
      - APACHE_CONFIG_ENABLED=repositorios
      - SVN_REPOS=comerzzia
      - APACHE_SITES_ENABLED=app
    ports:
      - "8080:80"
    volumes:
      - apache_svn:/apps/repositorios/svn
    networks:
      - comerzzia_42
  backoffice:
    image: docker-repo.tier1.es:5043/producto/comerzzia/backoffice:4.2.1-SNAPSHOT
    environment:
      COMERZZIA_DB_CLASS: com.mysql.jdbc.Driver
      COMERZZIA_DB_DRIVER: mysql
      COMERZZIA_DB_PASS: comerzzia
      COMERZZIA_DB_URL: jdbc:mysql://db:3306/comerzzia
      COMERZZIA_DB_USER: comerzzia
      SLEEP: 30
    networks:
      - comerzzia_42
    depends_on:
      - db
      # db:
        # condition: service_healthy
  db:
    image: docker-repo.tier1.es:5043/producto/base-mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: comerzzia
      OTHER_DB_USERS: comerzzia,cmzportal,cmzportal-food
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - comerzzia_42
    # healthcheck:
    #   test: ["CMD", "mysql", "-pcomerzzia", "--host=localhost", "--port=3306", "-e 'SELECT 1'"]
      # interval: 1m30s
      # timeout: 10s
      # retries: 3
      # start_period: 40s
  db-updater:
    image: docker-repo.tier1.es:5043/contrib/db-updater:4.2
    environment:
      DST_DB_HOST: db
      DST_DB_USER: root
      DST_DB_PASS: comerzzia
      VERSION: 4.2
    depends_on:
      - db
    networks:
      - comerzzia_42

volumes:
  apache_svn: {}
  db_data: {}

networks:
  comerzzia_42:
