version: '2'
services:
  db-updater:
    image: eu.gcr.io/fresh-buffer-203111/contrib/db-updater
    command: ["import_url"]
    environment:
      URL: https://box.comerzzia.com/index.php/s/5RJkiKobEXQrjGN/download
      DST_DB_HOST: db
      DST_DB_USER: root
      DST_DB_PASS: comerzzia
      VERSION: ${STACK_NAME}
    networks:
      - comerzzia
    volumes:
      - /tmp/host_ip_address:/tmp/host_ip_address
  data-updater-nonfood:
    image: eu.gcr.io/fresh-buffer-203111/contrib/data-updater
    command: ["import_url"]
    environment:
      URL: https://box.comerzzia.com/index.php/s/9J9kSP6xstcxyYx/download
      MAP_UID: 10001
      DST_DIR:
    volumes:
      - ${STACK_NAME}_sol_liferay_data:/mnt
  data-updater-food:
    image: eu.gcr.io/fresh-buffer-203111/contrib/data-updater
    command: ["import_url"]
    environment:
      URL: https://box.comerzzia.com/index.php/s/qQMMZCPyoAKTGJA/download
      MAP_UID: 10001
      DST_DIR:
    volumes:
      - ${STACK_NAME}_sol_food_liferay_data:/mnt

networks:
  comerzzia:
    external:
      name: ${STACK_NAME}_default
