version: '2'
services:
  sol:
    image: eu.gcr.io/fresh-buffer-203111/producto/comerzzia/${CZZSOL_VERSION}
    environment:
      COMERZZIA_DB_CLASS: com.mysql.jdbc.Driver
      COMERZZIA_DB_URL: jdbc:mysql://db:3306/comerzzia
      COMERZZIA_DB_DRIVER: mysql
      COMERZZIA_DB_USER: comerzzia
      COMERZZIA_DB_PASS: comerzzia
      PORTAL_DB_URL: jdbc:mysql://db:3306/czzsol
      PORTAL_DB_DRIVER: mysql
      PORTAL_DB_PASS: czzsol
      PORTAL_DB_USER: czzsol
      JAVA_OPTS_MS: '512'
      JAVA_OPTS_MX: ${CZZ_MEMORY}
      SLEEP: 30
    ports:
      - "8090:8080"
    volumes:
      - ${CZZ_CORE_STACK_NAME}_sol_liferay_data:/apps/bin/jboss/standalone/liferay
    networks:
       - comerzzia

networks:
  comerzzia:
    external:
      name: ${CZZ_CORE_STACK_NAME}_default
