version: '2'
services:
  apache:
    image: eu.gcr.io/fresh-buffer-203111/producto/demo/comerzzia/apache:2.4
    environment:
      - APACHE_SITES_ENABLED=app
    ports:
      - "80:80"
    restart: always
  backoffice:
    image: eu.gcr.io/fresh-buffer-203111/producto/comerzzia/${CZZ_VERSION}
    environment:
      COMERZZIA_DB_CLASS: com.mysql.jdbc.Driver
      COMERZZIA_DB_DRIVER: mysql
      COMERZZIA_DB_PASS: comerzzia
      COMERZZIA_DB_URL: jdbc:mysql://db:3306/comerzzia
      COMERZZIA_DB_USER: comerzzia
      JAVA_OPTS_MS: '256'
      JAVA_OPTS_MX: '512'
      SLEEP: 30
    restart: always
    depends_on:
      - db
      # db:
        # condition: service_healthy
  db:
    image: eu.gcr.io/fresh-buffer-203111/producto/base-mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: comerzzia
      OTHER_DB_USERS: comerzzia,czzsol,czzsol-food,czzpos
    restart: always
    volumes:
      - ${STACK_NAME}_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    # healthcheck:
    #   test: ["CMD", "mysql", "-pcomerzzia", "--host=localhost", "--port=3306", "-e 'SELECT 1'"]
      # interval: 1m30s
      # timeout: 10s
      # retries: 3
      # start_period: 40s
