version: '2'
services:
  www-data-updater:
    image: eu.gcr.io/fresh-buffer-203111/contrib/data-updater
    command: ["import_url"]
    environment:
      URL: https://demo:jUrWdTp6VeTCIZnmlf1YxBaeJi0vB8@repo.saas.comerzzia.com/repositorios/CZZ_DEMO/${CZZ_VERSION}/demo-www/demo-www.zip
      MAP_UID:
      DST_DIR:
    volumes:
      - ${CZZ_CORE_STACK_NAME}_www_data:/mnt
  db-updater:
    image: eu.gcr.io/fresh-buffer-203111/contrib/db-updater
    command: ["import_url"]
    environment:
      URL: https://demo:jUrWdTp6VeTCIZnmlf1YxBaeJi0vB8@repo.saas.comerzzia.com/repositorios/CZZ_DEMO/${CZZ_DEMO_VERSION}/demo-data/db.zip
      DST_DB_HOST: db
      DST_DB_USER: root
      DST_DB_PASS: comerzzia
      VERSION: ${CZZ_CORE_STACK_NAME}
    networks:
      - comerzzia
    volumes:
      - /tmp/host_ip_address:/tmp/host_ip_address
  data-updater-nonfood:
    image: eu.gcr.io/fresh-buffer-203111/contrib/data-updater
    command: ["import_url"]
    environment:
      URL: https://demo:jUrWdTp6VeTCIZnmlf1YxBaeJi0vB8@repo.saas.comerzzia.com/repositorios/CZZ_DEMO/${CZZ_DEMO_VERSION}/demo-data/sol-document-library.zip
      MAP_UID: 10001
      DST_DIR:
    volumes:
      - ${CZZ_CORE_STACK_NAME}_sol_liferay_data:/mnt
  data-updater-food:
    image: eu.gcr.io/fresh-buffer-203111/contrib/data-updater
    command: ["import_url"]
    environment:
      URL: https://demo:jUrWdTp6VeTCIZnmlf1YxBaeJi0vB8@repo.saas.comerzzia.com/repositorios/CZZ_DEMO/${CZZ_DEMO_VERSION}/demo-data/sol-food-document-library.zip
      MAP_UID: 10001
      DST_DIR:
    volumes:
      - ${CZZ_CORE_STACK_NAME}_sol_food_liferay_data:/mnt

networks:
  comerzzia:
    external:
      name: ${CZZ_CORE_STACK_NAME}_default
