version: '2'
services:
  backoffice-outstore:
    image: eu.gcr.io/fresh-buffer-203111/producto/comerzzia/${CZZOUTSTORE_VERSION}
    environment:
      COMERZZIA_DB_URL: jdbc:mysql://db:3306/comerzzia
      COMERZZIA_DB_USER: comerzzia
      COMERZZIA_DB_PASS: comerzzia
      COMERZZIA_DB_CLASS: com.mysql.jdbc.Driver
      JAVA_OPTS: -Dvaadin.servlet.productionMode=true -XX:MaxRAM=${CZZ_MEMORY}m
    networks:
      - comerzzia

networks:
  comerzzia:
    external:
      name: ${CZZ_CORE_STACK_NAME}_default

